services:
  mysql:
    image: mysql:8.0
    container_name: tasks_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tasks_db
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
